# Generated by Django 4.2.1 on 2023-07-15 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_category_catparent_product_alternative'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product_alternative',
            options={'verbose_name': 'Product Alernative', 'verbose_name_plural': 'Product Alernatives'},
        ),
        migrations.CreateModel(
            name='product_Accessories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PACCAlternatives', models.ManyToManyField(related_name='Acscessories_Products', to='product.product')),
                ('PACCProduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mainAccessory_product', to='product.product')),
            ],
            options={
                'verbose_name': 'Product Accessory',
                'verbose_name_plural': 'Product Acessories',
            },
        ),
    ]
