# Generated by Django 4.2.1 on 2023-07-19 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_product_prddiimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='PRDDIImage',
            new_name='PRDDImage',
        ),
    ]
