# Generated by Django 4.2.1 on 2023-07-20 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_product_prdslug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='PRDISNew',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='PRDISbestSeller',
            field=models.BooleanField(default=False),
        ),
    ]
