# Generated by Django 4.2.1 on 2023-07-25 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_rename_prdslug_product_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='slug',
            new_name='PRDSlug',
        ),
    ]
