# Generated by Django 4.2.1 on 2023-07-25 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_rename_slug_product_prdslug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='PRDSlug',
            field=models.SlugField(blank=True, default=0, verbose_name='Product URL'),
            preserve_default=False,
        ),
    ]
