# Generated by Django 4.2.1 on 2023-07-29 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0020_alter_product_prdslug'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProudectImage',
            new_name='ProduectImage',
        ),
    ]
